version: '3.5'

services:
  app:
    build:
      context: .
    expose:
      - 5001
    network_mode: bridge
    ports:
      - 80:5000
    volumes:
      - ./app:/app
#networks:
 # proxynet:
#    name: bridge
